// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TRABALHOELETROPONTO.Data;

#nullable disable

namespace TRABALHOELETROPONTO.Migrations.ItensVenda
{
    [DbContext(typeof(ItensVendaContext))]
    [Migration("20231216175254_mig3")]
    partial class mig3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TRABALHOELETROPONTO.Models.ItensVenda", b =>
                {
                    b.Property<int>("ID_ITEM")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ID_CLIENTE")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ID_PRODUTO")
                        .HasColumnType("int");

                    b.Property<int?>("ID_VENDA")
                        .HasColumnType("int");

                    b.Property<int>("QUANTIDADE")
                        .HasColumnType("int");

                    b.Property<float>("SUBTOTAL")
                        .HasColumnType("float");

                    b.HasKey("ID_ITEM");

                    b.ToTable("ItensVenda");
                });
#pragma warning restore 612, 618
        }
    }
}
