// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TRABALHOELETROPONTO.Data;

#nullable disable

namespace TRABALHOELETROPONTO.Migrations.Venda
{
    [DbContext(typeof(VendaContext))]
    [Migration("20231216180205_mig5")]
    partial class mig5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TRABALHOELETROPONTO.Models.Venda", b =>
                {
                    b.Property<int>("ID_VENDA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DATA_VENDA")
                        .HasColumnType("datetime(6)");

                    b.Property<float>("DESCONTO")
                        .HasColumnType("float");

                    b.Property<string>("ID_CLIENTE")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool?>("PAGAMENTO_EFETUADO")
                        .HasColumnType("tinyint(1)");

                    b.Property<float>("TOTAL")
                        .HasColumnType("float");

                    b.HasKey("ID_VENDA");

                    b.ToTable("Venda");
                });
#pragma warning restore 612, 618
        }
    }
}
